import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Menu } from "@/components/menu";
import { Submenu } from "@/components/submenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Monitoramento de Ferramentas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Menu op1={"BOSCH"} op2={"Monitoramento de Ferramentas"}/>
        <Submenu op1={"Dashboard"} op2={"Usuários"} op3={"Ferramentas"} op4={"Histórico"}/>
        {children}
      </body>
    </html>
  );
}
